server:

  http_listen_port: 9080
  grpc_listen_port: 0

positions:

  filename: /tmp/positions.yaml

client:

  url: http://loki:3100/api/prom/push

scrape_configs:

  - job_name: remme_log
    entry_parser: raw
    static_configs:
    - targets:
        - localhost
      labels:
        job: remme_log
        __path__: /var/log/_data/*